### ISSUE TITLE
Starting from clean install (manually deleted all modular/mojo related folders) it fails somehow. Maybe somebody is encountering the same issue

### ISSUE THREAD

**Issue by Sharktheone** [Sharktheone/arch-mojo#2]
Starting from clean install (manually deleted all modular/mojo related folders) it fails somehow. Maybe somebody is encountering the same issue

```sh
$ mkdir -p /tmp/arch-mojo && curl -sSL https://raw.githubusercontent.com/Sharktheone/arch-mojo/main/install.py -o /tmp/arch-mojo/install.py && python /tmp/arch-mojo/install.py
Do you have modular already installed? (y/n): n
Do you want to install the libraries globally (for all users)? (y/n): n
Do you want to automatically use a venv when running modular install/update? (y/n): y
Where do you want to create the venv?: zsh

(...)

* `/home/mrk/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
== stdout ==

== stderr ==
/home/mrk/.modular/pkg/packages.modular.com_mojo/bin/lldb: error while loading shared libraries: libpanel.so.6: cannot open shared object file: No such file or directory

(...)
```

_Originally posted by @mdmrk in https://github.com/Sharktheone/arch-mojo/issues/1#issuecomment-1733130749_

**Comment by Sharktheone** [comment]
@mdmrk the issue you are experiencing is most likely because you didn't restart your shell. I've created this issue as a todo, so i add something that automatically restarts the shell or a note at the end of the script.

**Comment by hajsf** [comment]
Today I install fresh Arch Linux system, and got the same error, so it is not only with Manjaro:
```bash
Testing `MODULAR_HOME=/home/hajsf/.modular`
* `/home/hajsf/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
== stdout ==

== stderr ==
/home/hajsf/.modular/pkg/packages.modular.com_mojo/bin/lldb: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory

TEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/hajsf/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 378, in <module>
    main()
  File "/home/hajsf/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 374, in main
    tester.test(args.test_jupyter)
  File "/home/hajsf/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 311, in test
    self.test_mojo_repl()
  File "/home/hajsf/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 195, in test_mojo_repl
    assert False
AssertionError
modular: error: failed to run python: 
```
And
```bach
[hajsf@archlinux ~]$ mojo
/home/hajsf/.modular/pkg/packages.modular.com_mojo/bin/lldb: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
```

**Comment by Sharktheone** [comment]
This is now a completely other error than before. You are missing another library, but this is shipped with pacman. You can install it with `sudo pacman -S libbsd`

**Comment by Rqbln** [comment]
After successfully installing mojo in 0.2.9, i broke my installation, now i can't reinstall it :/

 ```
Found release for https://packages.modular.com/mojo @ 0.3.0, installing to /home/rqbin/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/MDMV5anc4n6047Xv-XWXpvoM7rOAMjiWsiMAzyhlBOc with cURL error SSL connect error - Looking for MDMV5anc4n6047Xv-XWXpvoM7rOAMjiWsiMAzyhlBOc
```

**Comment by Sharktheone** [comment]
> After successfully installing mojo in 0.2.9, i broke my installation, now i can't reinstall it :/

This seems more like a problem on the modular side, since modular is trying to download something with cURL and it fails with "error SSL connect error".

**Comment by zyper86** [comment]
What is the output of echo $LD_LIBRARY_PATH and does 'successfully installing mojo' mean that everything works?

**Comment by Sharktheone** [comment]
`LD_LIBRARY_PATH` should be set to something like `/home/<user>/.local/lib/mojo`.

The message "successfully installing mojo" probably comes from the mojo/modular side, since I don't print this message somewhere in this script. Modular is unaware of the situation, you're installing mojo, this means for example it doesn't know that you needed to install some extra libraries to get mojo running. So when there something is messed up, it still can't work.

This means, in this case things can still go wrong even tough everything looks fine for modular.
